
spring:
  datasource:
    url: "jdbc:mysql://localhost/liberary"
    username: "root"
    password: "1234"
    driver-class-git name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        disable_sql_comments: org.hibernate.dialect.MySQL8Dialect

